[build-system]
requires = ["setuptools>=82.0.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ollama-agent"
version = "0.3.2"
description = "Agente de IA para interactuar con modelos de lenguaje locales a través de Ollama"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepagents==0.5.3",
    "langchain==1.2.15",
    "langchain-ollama==1.1.0",
    "langgraph==1.1.8",
    "langchain-mcp-adapters==0.2.2",
    "PyYAML==6.0.3",
    "openai==2.32.0",
    "ollama==0.6.1",
    "mem0ai==2.0.0",
    "mss==10.1.0",
    "Pillow==12.2.0",
    "prompt_toolkit==3.0.52",
    "qdrant-client==1.17.1",
    "rich==15.0.0",
    "mcp==1.23.0",
]

[project.scripts]
ollama-agent = "ollama_agent.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["ollama_agent*"]

[tool.setuptools.package-data]
ollama_agent = ["settings/default_instructions.md"]
